[user]
left_paddle_algorithm = "neat"
right_paddle_algorithm = "human"
menu_enable = true

[graphics]
graphic_enable = true
width = 720
height = 720
fps = 120
title = "Pong"
countdown_enable = false
icon_path = "asset/images/menu/icon.jpg"

[game]
max_score = 10
paddle_width = 10
paddle_height = 100
paddle_speed = 5
ball_radius = 10
ball_speed = 3
ball_speed_increase_ratio = 1.05
ball_speed_max = 10

[item]
item_enable = true
item_spawn_rate = 0.005
max_item = 1
item_duration = 1000

[ball_chaser]
ball_chaser_tolerance_ratio = 0.2

[neat]
train_enable = false
restore_enable = false
config_path = "config/neat_config.txt"
restore_path = "model/neat/checkpoint-0"
play_path = "model/neat/saved_model"
max_generations = 50